[package]
name = "connectivity-apis"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
futures-util = "0.3"
bytes = "1.4"

tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.17"
